name: c3aidatalake-notebooks-env
channels:
  - conda-forge
dependencies:
  - python=3.7.*
  - numpy
  - matplotlib
  - pandas=1.0.*
  - requests
  - scipy
  - r-base
  - r-httr
  - r-tidyverse
  - r-jsonlite